name: Deploy React App
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to GH Pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://${{ d449e82f60db42a98e8f3b880de26d031ff9f82a }}@github.com/${{ https://github.com/Balqees-401-advanced-javascript/DeployReset/tree/master }}.git
        npm install
        npm run deploy